# Generated by Django 3.2.7 on 2021-09-09 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': [('administrator_access', 'Administrator access'), ('customer_access', 'Customer accesss')]},
        ),
    ]
